route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 2m
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'https://10.0.0.1:8888/v1/alert/trigger/'
    send_resolved: true
    http_config:
      tls_config:
        insecure_skip_verify: true
      authorization:
        type: Token
        credentials: 820923a1a2dad74e8d279c48b8a1160c
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
